# Generated by Django 3.0.6 on 2021-04-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_aadharcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weatherdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
    ]
