# Generated by Django 3.0.6 on 2021-04-05 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_weatherdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
