# Generated by Django 3.2 on 2021-04-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_farmorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmorder',
            name='category1',
            field=models.CharField(default='Cereals', max_length=20),
        ),
    ]
