# Generated by Django 3.1.7 on 2021-03-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo_main', '0013_auto_20181117_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='three',
            name='Stock',
        ),
    ]
