# Generated by Django 3.0.6 on 2021-03-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classify', '0003_auto_20200708_0921'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
